create table tdspr_pessoa (
    id number generated by default as identity primary key,
    nome varchar2(100) not null,
    telefone varchar2(20) unique,
    cpf varchar2(14) unique
)

create table tdspr_endereco (
    id number generated by default as identity primary key,
    logradouro varchar2(100) not null,
    complemento varchar2(100),
    numero varchar2(10) not null,
    bairro varchar2(50) not null,
    cep varchar2(10) not null,
    municipio varchar2(50) not null,
    pessoa_id number not null,
    constraint fk_pessoa foreign key (pessoa_id) references tdspr_pessoa (id)
)